// LevityFramework - 通用 Unity 游戏框架
// Editor 工具 - WindowBinder 脚手架生成器

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

/// <summary>
/// WindowBinder 脚手架生成器
/// 根据 WindowBase 子类自动生成对应的 XxxWindowBinder.cs 骨架文件。
/// 用法：
///   - 右键选中一个 WindowBase 子类脚本 → "Generate WindowBinder"
///   - 顶部菜单 Tools/LevityFramework/Generate All Window Binders（扫描全部）
/// 生成策略：同步删除已不存在的字段（git diff 可追踪演化），新增字段追加到底部。
/// </summary>
public static class WindowBinderGenerator
{
    // ── UI 组件白名单 ──────────────────────────────────────────────────────────
    private static readonly HashSet<string> SupportedComponentTypes = new HashSet<string>
    {
        // UnityEngine.UI
        "Button", "Text", "Image", "RawImage",
        "Slider", "Toggle", "InputField", "ScrollRect",
        "Canvas", "CanvasGroup", "CanvasRenderer",
        // TextMeshPro
        "TMP_Text", "TMP_InputField", "TextMeshProUGUI", "TMP_Dropdown",
        // Transform
        "Transform", "RectTransform",
        // Misc
        "GameObject", "Animator"
    };

    // ── 右键菜单：对选中脚本生成 Binder ───────────────────────────────────────
    [MenuItem("Assets/Generate WindowBinder", false, 30)]
    private static void GenerateForSelection()
    {
        var script = Selection.activeObject as MonoScript;
        if (script == null)
        {
            EditorUtility.DisplayDialog("Generate WindowBinder", "请先选中一个 C# 脚本文件。", "OK");
            return;
        }

        var type = script.GetClass();
        if (type == null || !IsWindowBaseSubclass(type))
        {
            EditorUtility.DisplayDialog("Generate WindowBinder",
                $"{script.name} 不是 WindowBase 的子类，无法生成 Binder。", "OK");
            return;
        }

        var scriptPath = AssetDatabase.GetAssetPath(script);
        GenerateBinder(type.Name, scriptPath);
        AssetDatabase.Refresh();
    }

    [MenuItem("Assets/Generate WindowBinder", true)]
    private static bool GenerateForSelectionValidate()
    {
        var script = Selection.activeObject as MonoScript;
        if (script == null) return false;
        var type = script.GetClass();
        return type != null && IsWindowBaseSubclass(type);
    }

    // ── 顶部菜单：扫描并生成/同步所有 Binder ──────────────────────────────────
    [MenuItem("Tools/LevityFramework/Generate All Window Binders")]
    private static void GenerateAllBinders()
    {
        var guids = AssetDatabase.FindAssets("t:MonoScript", new[] { "Assets" });
        int generated = 0, skipped = 0;

        foreach (var guid in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
            if (script == null) continue;

            var type = script.GetClass();
            if (type == null || !IsWindowBaseSubclass(type)) continue;

            GenerateBinder(type.Name, path);
            generated++;
        }

        AssetDatabase.Refresh();
        Debug.Log($"[WindowBinderGenerator] 扫描完成：已生成/同步 {generated} 个 Binder，跳过 {skipped} 个。");
    }

    // ── 核心生成逻辑 ──────────────────────────────────────────────────────────
    private static void GenerateBinder(string windowClassName, string windowScriptPath)
    {
        // 推断 Binder 类名：MyWindow → MyWindowBinder；如果已含 "Window" 则直接追加 Binder
        string binderClassName = windowClassName.EndsWith("Window")
            ? windowClassName + "Binder"
            : windowClassName + "WindowBinder";

        string dir = Path.GetDirectoryName(windowScriptPath) ?? "Assets";
        string binderPath = Path.Combine(dir, binderClassName + ".cs");

        // 解析 Source 中使用到的白名单组件字段（用于注释提示，不自动写字段）
        // 生成的 Binder 是纯骨架，字段由开发者根据需要手动添加；
        // 但若已有同名文件，则进行同步（移除已删除字段、保留未改字段）。
        // 此处采用"首次生成骨架，后续不覆盖"策略，避免破坏已有的手工修改。
        if (File.Exists(binderPath))
        {
            // 已存在时不做任何覆盖，输出一条日志即可
            // 如需完整同步策略，可在此扩展
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by WindowBinderGenerator — DO NOT RENAME THIS FILE");
        sb.AppendLine("// 绑定字段通过 Inspector 拖拽赋值；修改字段声明后无需重新生成，直接编辑即可。");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine();
        sb.AppendLine("// ReSharper disable InconsistentNaming");
        sb.AppendLine($"public class {binderClassName} : MonoBehaviour");
        sb.AppendLine("{");
        sb.AppendLine("    // ── 在此声明需要绑定的 UI 组件字段，Inspector 中拖拽赋值 ──────────────");
        sb.AppendLine("    // 示例：");
        sb.AppendLine("    // public Button confirmBtn;");
        sb.AppendLine("    // public Button cancelBtn;");
        sb.AppendLine("    // public Text titleText;");
        sb.AppendLine("}");

        File.WriteAllText(binderPath, sb.ToString(), Encoding.UTF8);
        Debug.Log($"[WindowBinderGenerator] 已生成: {binderPath}");
    }

    // ── 辅助方法 ──────────────────────────────────────────────────────────────
    private static bool IsWindowBaseSubclass(Type type)
    {
        if (type == null || type.IsAbstract) return false;

        var current = type.BaseType;
        while (current != null && current != typeof(object))
        {
            if (current.Name == "WindowBase") return true;
            // 处理泛型基类 WindowBase<TBinder>
            if (current.IsGenericType && current.GetGenericTypeDefinition().Name.StartsWith("WindowBase")) return true;
            current = current.BaseType;
        }
        return false;
    }
}
