// AUTO-GENERATED by WindowBinderGenerator — DO NOT RENAME THIS FILE
// 绑定字段通过 Inspector 拖拽赋值；修改字段声明后无需重新生成，直接编辑即可。

using UnityEngine;
using UnityEngine.UI;

// ReSharper disable InconsistentNaming
public class SettingsWindowBinder : MonoBehaviour
{
    public Slider bgmVolumeSlider;
    public Slider sfxVolumeSlider;
    public Slider voiceVolumeSlider;
    public Slider textSpeedSlider;
    public Slider autoDelaySlider;
    public Button closeButton;
}
